import type { SentenceVisualCue } from "@/lib/types";

/**
 * Curated Sentence-by-Sentence Visual Photo Guidance (NEO Study Dual-Coding Engine)
 * Maps exact sentences across all 15 Core Lessons (Stages 1-5) to locked character avatars,
 * action tags, setting descriptions, and distinct illustration assets.
 */
export const LESSON_SENTENCE_VISUALS: Record<string, SentenceVisualCue[]> = {
  // ── STAGE 1 ─────────────────────────────────────────────────────────────────
  // Lesson 1: The New Classmate
  "1-1": [
    {
      sentence_id: "1-1-1",
      lesson_id: 1,
      page_number: 1,
      sentence_text: "It was Monday morning. Mia walked slowly into her new classroom.",
      speaker: "Mia (New Student)",
      speaker_avatar: "👧",
      scene_title: "Mia Enters Classroom",
      scene_image_url: "/images/stories/l1_s1.jpg",
      action_tag: "🚪 Entering Classroom",
      cue_color: "blue",
    },
    {
      sentence_id: "1-1-2",
      lesson_id: 1,
      page_number: 1,
      sentence_text: "She held her school bag tightly and looked around.",
      speaker: "Mia (Nervous Feeling)",
      speaker_avatar: "🎒",
      scene_title: "Holding Bag Tightly",
      scene_image_url: "/images/stories/l1_s2.jpg",
      action_tag: "🎒 Clutches Backpack",
      cue_color: "indigo",
    },
    {
      sentence_id: "1-1-3",
      lesson_id: 1,
      page_number: 1,
      sentence_text: "Mrs. Reyes smiled at her. \"Class, we have a new student today. Her name is Mia.\"",
      speaker: "Mrs. Reyes (Teacher)",
      speaker_avatar: "👩‍🏫",
      scene_title: "Teacher Introduction",
      scene_image_url: "/images/stories/l1_s3.jpg",
      action_tag: "👩‍🏫 Warm Welcome",
      cue_color: "emerald",
    },
    {
      sentence_id: "1-1-4",
      lesson_id: 1,
      page_number: 1,
      sentence_text: "\"Good morning, Mia!\" the class said. Mia smiled, but she still felt nervous.",
      speaker: "Grade 3 Classmates",
      speaker_avatar: "👋",
      scene_title: "Class Greeting",
      scene_image_url: "/images/stories/l1_s4.jpg",
      action_tag: "👋 Friendly Chorus",
      cue_color: "amber",
    },
  ],
  "1-2": [
    {
      sentence_id: "1-2-1",
      lesson_id: 1,
      page_number: 2,
      sentence_text: "During recess, Mia sat alone under a tree. She watched the other children play.",
      speaker: "Mia (Sitting Alone)",
      speaker_avatar: "🌳",
      scene_title: "Under the Acacia Tree",
      scene_image_url: "/images/stories/l1_s5.jpg",
      action_tag: "🌳 Shady Recess",
      cue_color: "emerald",
    },
    {
      sentence_id: "1-2-2",
      lesson_id: 1,
      page_number: 2,
      sentence_text: "Anna noticed her. \"Would you like to play with us?\" Anna asked.",
      speaker: "Anna (Kind Classmate)",
      speaker_avatar: "🧒",
      scene_title: "Anna Reaches Out",
      scene_image_url: "/images/stories/l1_s6.jpg",
      action_tag: "🤝 Invitation to Play",
      cue_color: "amber",
    },
    {
      sentence_id: "1-2-3",
      lesson_id: 1,
      page_number: 2,
      sentence_text: "Mia looked surprised. \"Yes, please,\" she answered.",
      speaker: "Mia (Surprised & Relieved)",
      speaker_avatar: "✨",
      scene_title: "Joyful Response",
      scene_image_url: "/images/stories/l1_s6.jpg",
      action_tag: "✨ Accepts with Joy",
      cue_color: "purple",
    },
    {
      sentence_id: "1-2-4",
      lesson_id: 1,
      page_number: 2,
      sentence_text: "Anna introduced Mia to her friends. They played together until the bell rang.",
      speaker: "Anna & Playground Friends",
      speaker_avatar: "🎈",
      scene_title: "Playground Circle Game",
      scene_image_url: "/images/stories/l1_s7.jpg",
      action_tag: "🎈 Playing Together",
      cue_color: "blue",
    },
    {
      sentence_id: "1-2-5",
      lesson_id: 1,
      page_number: 2,
      sentence_text: "\"Thank you for inviting me,\" Mia said. Anna replied, \"Everyone needs a friend.\" Mia returned to the classroom feeling much happier.",
      speaker: "Mia & Anna (True Friends)",
      speaker_avatar: "💖",
      scene_title: "Friendship Complete",
      scene_image_url: "/images/stories/l1_s8.jpg",
      action_tag: "💖 Happy New Friend",
      cue_color: "pink",
    },
  ],

  // Lesson 2: Sharing My Lunch
  "2-1": [
    {
      sentence_id: "2-1-1",
      lesson_id: 2,
      page_number: 1,
      sentence_text: "Ben opened his lunch box during recess. His mother had packed rice, chicken, and mango slices.",
      speaker: "Ben (Lunch Time)",
      speaker_avatar: "🍱",
      scene_title: "Packed Lunchbox",
      scene_image_url: "/images/stories/l2_s1.jpg",
      action_tag: "🍱 Opening Lunch",
      cue_color: "amber",
    },
    {
      sentence_id: "2-1-2",
      lesson_id: 2,
      page_number: 1,
      sentence_text: "Beside him sat his friend Leo. Leo opened his school bag and looked inside. Then he sighed.",
      speaker: "Leo (Sad Friend)",
      speaker_avatar: "👦",
      scene_title: "Leo Sits Beside",
      scene_image_url: "/images/stories/l2_s2.jpg",
      action_tag: "😔 Empty Bag",
      cue_color: "blue",
    },
    {
      sentence_id: "2-1-3",
      lesson_id: 2,
      page_number: 1,
      sentence_text: "\"What happened?\" Ben asked. \"I left my lunch at home,\" Leo said.",
      speaker: "Ben & Leo Dialogue",
      speaker_avatar: "💬",
      scene_title: "Forgotten Lunch",
      scene_image_url: "/images/stories/l2_s3.jpg",
      action_tag: "💬 Caring Question",
      cue_color: "purple",
    },
  ],
  "2-2": [
    {
      sentence_id: "2-2-1",
      lesson_id: 2,
      page_number: 2,
      sentence_text: "Ben looked at his food. He remembered something his mother often told him: \"If you have enough, it is good to share.\"",
      speaker: "Ben (Remembering Mother's Advice)",
      speaker_avatar: "💡",
      scene_title: "Mother's Wisdom",
      scene_image_url: "/images/stories/l2_s4.jpg",
      action_tag: "💡 Thought of Kindness",
      cue_color: "emerald",
    },
    {
      sentence_id: "2-2-2",
      lesson_id: 2,
      page_number: 2,
      sentence_text: "Ben divided his food into two parts. \"You can have some of mine,\" he said.",
      speaker: "Ben (Sharing Food)",
      speaker_avatar: "🍗",
      scene_title: "Dividing the Lunch",
      scene_image_url: "/images/stories/l2_s5.jpg",
      action_tag: "🍗 Generous Share",
      cue_color: "amber",
    },
    {
      sentence_id: "2-2-3",
      lesson_id: 2,
      page_number: 2,
      sentence_text: "Leo smiled. \"Thank you!\" The two boys ate together. They talked and laughed until recess was over.",
      speaker: "Ben & Leo Eating Together",
      speaker_avatar: "😄",
      scene_title: "Eating & Laughing",
      scene_image_url: "/images/stories/l2_s6.jpg",
      action_tag: "😄 Joyful Meal",
      cue_color: "blue",
    },
    {
      sentence_id: "2-2-4",
      lesson_id: 2,
      page_number: 2,
      sentence_text: "When Ben went home, he told his mother what happened. His mother smiled. \"You made a kind choice today,\" she said.",
      speaker: "Ben's Mother (Proud Praise)",
      speaker_avatar: "👩",
      scene_title: "Kind Choice Rewarded",
      scene_image_url: "/images/stories/l2_s7.jpg",
      action_tag: "🌟 Mother's Praise",
      cue_color: "rose",
    },
  ],

  // Lesson 3: A Friend in Need
  "3-1": [
    {
      sentence_id: "3-1-1",
      lesson_id: 3,
      page_number: 1,
      sentence_text: "After class, Sofia saw her friend Ella carrying many books. One book fell to the floor. Then another one fell.",
      speaker: "Sofia & Ella",
      speaker_avatar: "📚",
      scene_title: "Heavy Books Falling",
      scene_image_url: "/images/stories/l3_s1.jpg",
      action_tag: "📚 Dropped Books",
      cue_color: "amber",
    },
    {
      sentence_id: "3-1-2",
      lesson_id: 3,
      page_number: 1,
      sentence_text: "\"Wait, Ella!\" Sofia called. Sofia picked up the books.",
      speaker: "Sofia Helping",
      speaker_avatar: "🤝",
      scene_title: "Picking Up Books",
      scene_image_url: "/images/stories/l3_s2.jpg",
      action_tag: "🤝 Helping Hand",
      cue_color: "blue",
    },
    {
      sentence_id: "3-1-3",
      lesson_id: 3,
      page_number: 1,
      sentence_text: "\"Thank you,\" Ella said. \"They are too heavy for me.\" \"I'll help you carry them,\" Sofia said. Together, they walked to the library.",
      speaker: "Walking to Library",
      speaker_avatar: "🏛️",
      scene_title: "Library Pathway",
      scene_image_url: "/images/stories/l3_s3.jpg",
      action_tag: "🏛️ Library Walk",
      cue_color: "emerald",
    },
  ],
  "3-2": [
    {
      sentence_id: "3-2-1",
      lesson_id: 3,
      page_number: 2,
      sentence_text: "The next day, Sofia had trouble answering a math activity. Ella noticed that Sofia looked confused.",
      speaker: "Sofia in Class",
      speaker_avatar: "📐",
      scene_title: "Math Confusion",
      scene_image_url: "/images/stories/l3_s4.jpg",
      action_tag: "📐 Math Activity",
      cue_color: "rose",
    },
    {
      sentence_id: "3-2-2",
      lesson_id: 3,
      page_number: 2,
      sentence_text: "\"Would you like some help?\" Ella asked. \"Yes, please,\" Sofia replied.",
      speaker: "Ella Offering Help",
      speaker_avatar: "✨",
      scene_title: "Mutual Friendship",
      scene_image_url: "/images/stories/l3_s5.jpg",
      action_tag: "✨ Helping with Steps",
      cue_color: "purple",
    },
    {
      sentence_id: "3-2-3",
      lesson_id: 3,
      page_number: 2,
      sentence_text: "Ella explained the activity slowly. Sofia smiled after she understood it. \"Thank you.\" Ella smiled back. \"Friends help each other.\"",
      speaker: "Friends Supporting Each Other",
      speaker_avatar: "💖",
      scene_title: "Friends Helping",
      scene_image_url: "/images/stories/l3_s6.jpg",
      action_tag: "💖 True Friendship",
      cue_color: "pink",
    },
  ],

  // ── STAGE 2 ─────────────────────────────────────────────────────────────────
  // Lesson 4: My Morning Routine
  "4-1": [
    {
      sentence_id: "4-1-1",
      lesson_id: 4,
      page_number: 1,
      sentence_text: "Every school day, Carlo wakes up at six o'clock. First, he makes his bed.",
      speaker: "Carlo (Morning)",
      speaker_avatar: "⏰",
      scene_title: "Waking Up at Six",
      scene_image_url: "/images/stories/l4_s1.jpg",
      action_tag: "⏰ Making Bed",
      cue_color: "blue",
    },
    {
      sentence_id: "4-1-2",
      lesson_id: 4,
      page_number: 1,
      sentence_text: "Next, he brushes his teeth and takes a bath. Then, Carlo puts on his school uniform.",
      speaker: "Carlo (Getting Ready)",
      speaker_avatar: "🪥",
      scene_title: "Brushing & Uniform",
      scene_image_url: "/images/stories/l4_s2.jpg",
      action_tag: "🪥 Morning Hygiene",
      cue_color: "emerald",
    },
    {
      sentence_id: "4-1-3",
      lesson_id: 4,
      page_number: 1,
      sentence_text: "After getting dressed, he eats breakfast with his family.",
      speaker: "Carlo with Family",
      speaker_avatar: "🍳",
      scene_title: "Nutritious Breakfast",
      scene_image_url: "/images/stories/l4_s3.jpg",
      action_tag: "🍳 Healthy Meal",
      cue_color: "amber",
    },
  ],
  "4-2": [
    {
      sentence_id: "4-2-1",
      lesson_id: 4,
      page_number: 2,
      sentence_text: "Before leaving the house, Carlo checks his school bag. He makes sure his notebooks, pencils, homework, and water bottle are inside.",
      speaker: "Carlo Checking Bag",
      speaker_avatar: "🎒",
      scene_title: "Checking Supplies",
      scene_image_url: "/images/stories/l4_s4.jpg",
      action_tag: "🎒 Organized Bag",
      cue_color: "purple",
    },
    {
      sentence_id: "4-2-2",
      lesson_id: 4,
      page_number: 2,
      sentence_text: "Finally, he says goodbye to his parents and walks to school with his older sister.",
      speaker: "Carlo & Sister",
      speaker_avatar: "🚶‍♂️",
      scene_title: "Walking to School",
      scene_image_url: "/images/stories/l4_s5.jpg",
      action_tag: "🚶‍♂️ Safe Commute",
      cue_color: "blue",
    },
    {
      sentence_id: "4-2-3",
      lesson_id: 4,
      page_number: 2,
      sentence_text: "From that day on, Carlo made sure to follow every step of his morning routine.",
      speaker: "Carlo (Routine Mastery)",
      speaker_avatar: "🌟",
      scene_title: "Morning Habit Complete",
      scene_image_url: "/images/stories/l4_s5.jpg",
      action_tag: "🌟 Daily Discipline",
      cue_color: "emerald",
    },
  ],

  // Lesson 5: The Forgotten Homework
  "5-1": [
    {
      sentence_id: "5-1-1",
      lesson_id: 5,
      page_number: 1,
      sentence_text: "Liam came home from school and placed his bag beside the sofa. \"I'll do my homework later,\" he said.",
      speaker: "Liam (Arriving Home)",
      speaker_avatar: "🛋️",
      scene_title: "Bag Beside Sofa",
      scene_image_url: "/images/stories/l5_s1.jpg",
      action_tag: "🛋️ Delayed Duty",
      cue_color: "amber",
    },
    {
      sentence_id: "5-1-2",
      lesson_id: 5,
      page_number: 1,
      sentence_text: "Instead, he played with his toys. After dinner, Liam watched television. Soon, he became sleepy and went to bed.",
      speaker: "Liam Playing Toys",
      speaker_avatar: "🎮",
      scene_title: "Playing Toys",
      scene_image_url: "/images/stories/l5_s2.jpg",
      action_tag: "🎮 Distractions",
      cue_color: "rose",
    },
    {
      sentence_id: "5-1-3",
      lesson_id: 5,
      page_number: 1,
      sentence_text: "The next morning, their teacher said, \"Please pass your homework.\" Liam suddenly remembered his unfinished work. He felt embarrassed.",
      speaker: "Liam in Class",
      speaker_avatar: "😳",
      scene_title: "Morning Embarrassment",
      scene_image_url: "/images/stories/l5_s3.jpg",
      action_tag: "😳 Forgot Homework",
      cue_color: "purple",
    },
  ],
  "5-2": [
    {
      sentence_id: "5-2-1",
      lesson_id: 5,
      page_number: 2,
      sentence_text: "After class, Liam spoke to his teacher. \"I am sorry. I forgot to do my homework.\" His teacher nodded. \"What can you do differently tonight?\"",
      speaker: "Liam & Teacher",
      speaker_avatar: "🗣️",
      scene_title: "Teacher Advice",
      scene_image_url: "/images/stories/l5_s4.jpg",
      action_tag: "🗣️ Honest Apology",
      cue_color: "blue",
    },
    {
      sentence_id: "5-2-2",
      lesson_id: 5,
      page_number: 2,
      sentence_text: "\"I will finish my homework before I play,\" Liam answered. That afternoon, Liam went home and finished his homework first.",
      speaker: "Liam Working First",
      speaker_avatar: "📝",
      scene_title: "Homework Priority",
      scene_image_url: "/images/stories/l5_s4.jpg",
      action_tag: "📝 Responsibility",
      cue_color: "emerald",
    },
    {
      sentence_id: "5-2-3",
      lesson_id: 5,
      page_number: 2,
      sentence_text: "The next morning, he proudly passed his completed work.",
      speaker: "Liam (Proud Achiever)",
      speaker_avatar: "🌟",
      scene_title: "Completed Homework",
      scene_image_url: "/images/stories/l5_s5.jpg",
      action_tag: "🌟 On-Time Success",
      cue_color: "amber",
    },
  ],

  // Lesson 6: Keeping Our Classroom Clean
  "6-1": [
    {
      sentence_id: "6-1-1",
      lesson_id: 6,
      page_number: 1,
      sentence_text: "The Grade 3 class had just finished an art activity. Pieces of paper were scattered on the floor. Crayons were left on the tables.",
      speaker: "Classroom Scene",
      speaker_avatar: "🎨",
      scene_title: "Scattered Art Paper",
      scene_image_url: "/images/stories/l6_s1.jpg",
      action_tag: "🎨 Art Clutter",
      cue_color: "amber",
    },
    {
      sentence_id: "6-1-2",
      lesson_id: 6,
      page_number: 1,
      sentence_text: "The students prepared to leave. Maria looked around. \"Our room is messy,\" she said. She picked up paper near her desk.",
      speaker: "Maria (Taking Initiative)",
      speaker_avatar: "🧹",
      scene_title: "Maria Tidying",
      scene_image_url: "/images/stories/l6_s2.jpg",
      action_tag: "🧹 Picking Up Waste",
      cue_color: "emerald",
    },
  ],
  "6-2": [
    {
      sentence_id: "6-2-1",
      lesson_id: 6,
      page_number: 2,
      sentence_text: "Paolo saw her and began arranging the chairs. Grace returned the crayons and other art materials to the shelf.",
      speaker: "Paolo & Grace",
      speaker_avatar: "🖍️",
      scene_title: "Arranging Supplies",
      scene_image_url: "/images/stories/l6_s3.jpg",
      action_tag: "🖍️ Teamwork",
      cue_color: "blue",
    },
    {
      sentence_id: "6-2-2",
      lesson_id: 6,
      page_number: 2,
      sentence_text: "Their teacher nodded. \"This room belongs to all of us. Taking care of it is everyone's responsibility.\" The room was sparkling clean.",
      speaker: "Teacher & Class",
      speaker_avatar: "🏆",
      scene_title: "Clean Room Complete",
      scene_image_url: "/images/stories/l6_s4.jpg",
      action_tag: "🏆 Clean Classroom",
      cue_color: "purple",
    },
  ],

  // ── STAGE 3 ─────────────────────────────────────────────────────────────────
  // Lesson 7: The Lost Pencil
  "7-1": [
    {
      sentence_id: "7-1-1",
      lesson_id: 7,
      page_number: 1,
      sentence_text: "Joshua noticed a shiny blue pencil under his desk. It had a small rocket printed on the side. He picked it up.",
      speaker: "Joshua (Discoverer)",
      speaker_avatar: "✏️",
      scene_title: "Shiny Rocket Pencil",
      scene_image_url: "/images/stories/l7_s1.jpg",
      action_tag: "✏️ Found Pencil",
      cue_color: "blue",
    },
    {
      sentence_id: "7-1-2",
      lesson_id: 7,
      page_number: 1,
      sentence_text: "A few minutes later, Daniel searched inside his school bag. \"My pencil is missing. My father gave it to me for my birthday.\"",
      speaker: "Daniel (Worried)",
      speaker_avatar: "🔍",
      scene_title: "Daniel Searching",
      scene_image_url: "/images/stories/l7_s2.jpg",
      action_tag: "🔍 Missing Special Gift",
      cue_color: "rose",
    },
  ],
  "7-2": [
    {
      sentence_id: "7-2-1",
      lesson_id: 7,
      page_number: 2,
      sentence_text: "Joshua stood up. \"Daniel, is this yours?\" Daniel's eyes became bright. \"Yes! I thought I lost it forever.\"",
      speaker: "Joshua Returning",
      speaker_avatar: "🤝",
      scene_title: "Returning the Pencil",
      scene_image_url: "/images/stories/l7_s3.jpg",
      action_tag: "🤝 Honest Action",
      cue_color: "emerald",
    },
    {
      sentence_id: "7-2-2",
      lesson_id: 7,
      page_number: 2,
      sentence_text: "Joshua smiled. He realized that returning the pencil made him feel better than keeping something that was not his.",
      speaker: "Joshua (Integrity)",
      speaker_avatar: "💖",
      scene_title: "Integrity Feels Good",
      scene_image_url: "/images/stories/l7_s4.jpg",
      action_tag: "💖 Honesty Rewarded",
      cue_color: "pink",
    },
  ],

  // Lesson 8: The Broken Flower Pot
  "8-1": [
    {
      sentence_id: "8-1-1",
      lesson_id: 8,
      page_number: 1,
      sentence_text: "One Saturday afternoon, Nina played with a ball outside. Her mother had said, \"Please do not play near the plants.\"",
      speaker: "Nina (Garden)",
      speaker_avatar: "⚽",
      scene_title: "Playing Near Plants",
      scene_image_url: "/images/stories/l8_s1.jpg",
      action_tag: "⚽ Ball Practice",
      cue_color: "amber",
    },
    {
      sentence_id: "8-1-2",
      lesson_id: 8,
      page_number: 1,
      sentence_text: "Crash! The ball hit her mother's flower pot. The pot broke into several pieces.",
      speaker: "Accident Scene",
      speaker_avatar: "💥",
      scene_title: "Broken Pot",
      scene_image_url: "/images/stories/l8_s2.jpg",
      action_tag: "💥 Flowerpot Crash",
      cue_color: "rose",
    },
  ],
  "8-2": [
    {
      sentence_id: "8-2-1",
      lesson_id: 8,
      page_number: 2,
      sentence_text: "Nina went inside. \"Mom, I broke your flower pot. I was playing too close. I'm sorry.\"",
      speaker: "Nina (Telling Truth)",
      speaker_avatar: "🗣️",
      scene_title: "Admitting Mistake",
      scene_image_url: "/images/stories/l8_s3.jpg",
      action_tag: "🗣️ Telling the Truth",
      cue_color: "blue",
    },
    {
      sentence_id: "8-2-2",
      lesson_id: 8,
      page_number: 2,
      sentence_text: "Together, they carefully cleaned the broken pieces. Nina promised to play in a safer place next time.",
      speaker: "Mother & Nina",
      speaker_avatar: "🌱",
      scene_title: "Planting Together",
      scene_image_url: "/images/stories/l8_s4.jpg",
      action_tag: "🌱 Safe Play Promise",
      cue_color: "emerald",
    },
  ],

  // Lesson 9: The Extra Change
  "9-1": [
    {
      sentence_id: "9-1-1",
      lesson_id: 9,
      page_number: 1,
      sentence_text: "After school, Marco stopped at a small store to buy bread. He gave the shopkeeper fifty pesos.",
      speaker: "Marco (Bakery)",
      speaker_avatar: "🍞",
      scene_title: "Buying Bread",
      scene_image_url: "/images/stories/l9_s1.jpg",
      action_tag: "🍞 Store Counter",
      cue_color: "amber",
    },
    {
      sentence_id: "9-1-2",
      lesson_id: 9,
      page_number: 1,
      sentence_text: "Marco walked outside and counted the coins. He noticed that the shopkeeper had given him ten pesos too much.",
      speaker: "Marco Counting",
      speaker_avatar: "🪙",
      scene_title: "Extra Change Given",
      scene_image_url: "/images/stories/l9_s2.jpg",
      action_tag: "🪙 Counting Change",
      cue_color: "blue",
    },
  ],
  "9-2": [
    {
      sentence_id: "9-2-1",
      lesson_id: 9,
      page_number: 2,
      sentence_text: "Marco returned to the counter. \"Ma'am, you gave me too much change.\" The shopkeeper smiled and thanked him.",
      speaker: "Marco Returning Money",
      speaker_avatar: "🏪",
      scene_title: "Returning Ten Pesos",
      scene_image_url: "/images/stories/l9_s3.jpg",
      action_tag: "🏪 Honest Decision",
      cue_color: "emerald",
    },
    {
      sentence_id: "9-2-2",
      lesson_id: 9,
      page_number: 2,
      sentence_text: "As he walked home, Marco felt proud. He knew he had made the right decision.",
      speaker: "Marco (Proud Heart)",
      speaker_avatar: "🚶‍♂️",
      scene_title: "Walking Home Proud",
      scene_image_url: "/images/stories/l9_s4.jpg",
      action_tag: "🚶‍♂️ Moral Pride",
      cue_color: "purple",
    },
  ],

  // ── STAGE 4 ─────────────────────────────────────────────────────────────────
  // Lesson 10: Listening to Others
  "10-1": [
    {
      sentence_id: "10-1-1",
      lesson_id: 10,
      page_number: 1,
      sentence_text: "During class, Mrs. Santos divided the students into groups. Each group had to create a poster about nature.",
      speaker: "Lucas (Idea)",
      speaker_avatar: "🌲",
      scene_title: "Drawing Tree Idea",
      scene_image_url: "/images/stories/l10_s1.jpg",
      action_tag: "🌲 Tree Concept",
      cue_color: "emerald",
    },
    {
      sentence_id: "10-1-2",
      lesson_id: 10,
      page_number: 1,
      sentence_text: "Mrs. Santos said, \"Working in a group means listening to everyone.\" Maya apologized and listened to Lucas.",
      speaker: "Teacher Guidance",
      speaker_avatar: "👩‍🏫",
      scene_title: "Listening with Respect",
      scene_image_url: "/images/stories/l10_s2.jpg",
      action_tag: "👩‍🏫 Group Harmony",
      cue_color: "purple",
    },
  ],
  "10-2": [
    {
      sentence_id: "10-2-1",
      lesson_id: 10,
      page_number: 2,
      sentence_text: "The group combined their ideas. Their finished poster showed a large tree, animals, and students recycling.",
      speaker: "Group Collaboration",
      speaker_avatar: "🎨",
      scene_title: "Combined Nature Poster",
      scene_image_url: "/images/stories/l10_s3.jpg",
      action_tag: "🎨 Team Art",
      cue_color: "blue",
    },
    {
      sentence_id: "10-2-2",
      lesson_id: 10,
      page_number: 2,
      sentence_text: "Maya realized that listening helped the whole group create something much better.",
      speaker: "Maya & Team",
      speaker_avatar: "🌟",
      scene_title: "Poster Success",
      scene_image_url: "/images/stories/l10_s4.jpg",
      action_tag: "🌟 Shared Triumph",
      cue_color: "amber",
    },
  ],

  // Lesson 11: Helping at Home
  "11-1": [
    {
      sentence_id: "11-1-1",
      lesson_id: 11,
      page_number: 1,
      sentence_text: "When Ella entered the living room, her father was cleaning the kitchen and mother was washing clothes.",
      speaker: "Ella (Living Room)",
      speaker_avatar: "🏠",
      scene_title: "Family Chores",
      scene_image_url: "/images/stories/l11_s1.jpg",
      action_tag: "🏠 Busy Household",
      cue_color: "blue",
    },
    {
      sentence_id: "11-1-2",
      lesson_id: 11,
      page_number: 1,
      sentence_text: "Everyone was busy. \"Can I help?\" Ella asked with a smile.",
      speaker: "Ella Helping",
      speaker_avatar: "🍽️",
      scene_title: "Wiping Table",
      scene_image_url: "/images/stories/l11_s2.jpg",
      action_tag: "🍽️ Kitchen Chores",
      cue_color: "emerald",
    },
  ],
  "11-2": [
    {
      sentence_id: "11-2-1",
      lesson_id: 11,
      page_number: 2,
      sentence_text: "Ella helped fold clean clothes while her younger brother placed his toys in the box.",
      speaker: "Folding Clothes",
      speaker_avatar: "🧺",
      scene_title: "Folding Laundry",
      scene_image_url: "/images/stories/l11_s3.jpg",
      action_tag: "🧺 Fast Teamwork",
      cue_color: "pink",
    },
    {
      sentence_id: "11-2-2",
      lesson_id: 11,
      page_number: 2,
      sentence_text: "Because everyone helped, they finished early and watched a family movie together.",
      speaker: "Family Gathering",
      speaker_avatar: "🍿",
      scene_title: "Family Movie Time",
      scene_image_url: "/images/stories/l11_s4.jpg",
      action_tag: "🍿 Movie Time",
      cue_color: "amber",
    },
  ],

  // Lesson 12: We Can Be Different
  "12-1": [
    {
      sentence_id: "12-1-1",
      lesson_id: 12,
      page_number: 1,
      sentence_text: "Ana loved drawing, Miguel football, Samantha books, and Noah building models.",
      speaker: "Four Friends",
      speaker_avatar: "👥",
      scene_title: "Different Talents",
      scene_image_url: "/images/stories/l12_s1.jpg",
      action_tag: "👥 Unique Skills",
      cue_color: "purple",
    },
  ],
  "12-2": [
    {
      sentence_id: "12-2-1",
      lesson_id: 12,
      page_number: 2,
      sentence_text: "Ana drew pictures, Samantha wrote, Noah built a model, and Miguel organized the presentation.",
      speaker: "Team Collaboration",
      speaker_avatar: "🧩",
      scene_title: "Combining Strengths",
      scene_image_url: "/images/stories/l12_s2.jpg",
      action_tag: "🧩 Combined Power",
      cue_color: "emerald",
    },
    {
      sentence_id: "12-2-2",
      lesson_id: 12,
      page_number: 2,
      sentence_text: "Their classmates were impressed. Their differences had made the project better.",
      speaker: "Presentation Success",
      speaker_avatar: "👏",
      scene_title: "Applause and Praise",
      scene_image_url: "/images/stories/l12_s3.jpg",
      action_tag: "👏 Great Presentation",
      cue_color: "amber",
    },
  ],

  // ── STAGE 5 ─────────────────────────────────────────────────────────────────
  // Lesson 13: The Difficult Homework
  "13-1": [
    {
      sentence_id: "13-1-1",
      lesson_id: 13,
      page_number: 1,
      sentence_text: "Ava stared at the reading activity on her desk. She had already read the paragraph three times.",
      speaker: "Ava (Study Desk)",
      speaker_avatar: "📖",
      scene_title: "Difficult Activity",
      scene_image_url: "/images/stories/l13_s1.jpg",
      action_tag: "📖 Reading Hard Question",
      cue_color: "rose",
    },
    {
      sentence_id: "13-1-2",
      lesson_id: 13,
      page_number: 1,
      sentence_text: "Ava underlined the important words and looked for clues in the story.",
      speaker: "Ava Finding Clues",
      speaker_avatar: "🔍",
      scene_title: "Underlining Clues",
      scene_image_url: "/images/stories/l13_s2.jpg",
      action_tag: "🔍 Finding Context Clues",
      cue_color: "blue",
    },
  ],
  "13-2": [
    {
      sentence_id: "13-2-1",
      lesson_id: 13,
      page_number: 2,
      sentence_text: "Her brother showed Ava how to compare the question with the details in the passage.",
      speaker: "Brother Guiding",
      speaker_avatar: "💡",
      scene_title: "Brother's Guidance",
      scene_image_url: "/images/stories/l13_s3.jpg",
      action_tag: "💡 Smart Strategy",
      cue_color: "purple",
    },
    {
      sentence_id: "13-2-2",
      lesson_id: 13,
      page_number: 2,
      sentence_text: "Ava smiled. \"I found it!\" She had learned a better way to solve reading problems.",
      speaker: "Ava (Empowered)",
      speaker_avatar: "🎉",
      scene_title: "Problem Solved",
      scene_image_url: "/images/stories/l13_s4.jpg",
      action_tag: "🎉 Success!",
      cue_color: "emerald",
    },
  ],

  // Lesson 14: Learning to Ride a Bike
  "14-1": [
    {
      sentence_id: "14-1-1",
      lesson_id: 14,
      page_number: 1,
      sentence_text: "Daniel received a bicycle for his birthday. His father held the back of the seat to practice.",
      speaker: "Daniel & Father",
      speaker_avatar: "🚲",
      scene_title: "First Bicycle Ride",
      scene_image_url: "/images/stories/l14_s1.jpg",
      action_tag: "🚲 Starting to Pedal",
      cue_color: "blue",
    },
    {
      sentence_id: "14-1-2",
      lesson_id: 14,
      page_number: 1,
      sentence_text: "Daniel tried again. Each attempt he traveled a little farther on the park grass.",
      speaker: "Daniel Balancing",
      speaker_avatar: "🌱",
      scene_title: "Practicing Balance",
      scene_image_url: "/images/stories/l14_s2.jpg",
      action_tag: "🌱 Steady Progress",
      cue_color: "emerald",
    },
  ],
  "14-2": [
    {
      sentence_id: "14-2-1",
      lesson_id: 14,
      page_number: 2,
      sentence_text: "His father slowly let go. \"I'm riding by myself!\" Daniel shouted with confidence.",
      speaker: "Daniel Riding Solo",
      speaker_avatar: "🚀",
      scene_title: "Riding by Himself",
      scene_image_url: "/images/stories/l14_s4.jpg",
      action_tag: "🚀 Free Riding",
      cue_color: "amber",
    },
  ],

  // Lesson 15: The Reading Challenge
  "15-1": [
    {
      sentence_id: "15-1-1",
      lesson_id: 15,
      page_number: 1,
      sentence_text: "Clara decided to read for fifteen minutes every day, focusing on understanding words.",
      speaker: "Clara (Reading Challenge)",
      speaker_avatar: "📚",
      scene_title: "Daily Practice",
      scene_image_url: "/images/stories/l15_s1.jpg",
      action_tag: "📚 Reading Habit",
      cue_color: "purple",
    },
    {
      sentence_id: "15-1-2",
      lesson_id: 15,
      page_number: 1,
      sentence_text: "When she found difficult words, she checked the vocabulary guide and audio pronunciation.",
      speaker: "Clara Learning",
      speaker_avatar: "🎧",
      scene_title: "Audio Pronunciation",
      scene_image_url: "/images/stories/l15_s2.jpg",
      action_tag: "🎧 Phonics Audio",
      cue_color: "blue",
    },
  ],
  "15-2": [
    {
      sentence_id: "15-2-1",
      lesson_id: 15,
      page_number: 2,
      sentence_text: "At the end of the month, Clara read aloud with confidence and finished without giving up.",
      speaker: "Clara Reading Aloud",
      speaker_avatar: "🗣️",
      scene_title: "Confident Reading",
      scene_image_url: "/images/stories/l15_s3.jpg",
      action_tag: "🗣️ Fluent Voice",
      cue_color: "emerald",
    },
    {
      sentence_id: "15-2-2",
      lesson_id: 15,
      page_number: 2,
      sentence_text: "Her teacher smiled. \"You improved your reading and your confidence. Keep moving forward!\"",
      speaker: "Teacher & Clara",
      speaker_avatar: "🏆",
      scene_title: "Grand Reading Champion",
      scene_image_url: "/images/stories/l15_s4.jpg",
      action_tag: "🏆 Stage Champion",
      cue_color: "amber",
    },
  ],
};

/**
 * Retrieve sentence visual cues for any lesson page, with graceful automatic generation for any custom teacher story.
 */
export function getSentenceVisualCues(
  lessonId: number,
  pageNumber: number,
  pageContent?: string,
  pageImageUrl?: string
): SentenceVisualCue[] {
  const key = `${lessonId}-${pageNumber}`;
  if (LESSON_SENTENCE_VISUALS[key]) {
    return LESSON_SENTENCE_VISUALS[key];
  }

  // Graceful fallback generator for custom teacher stories or dynamic pages
  if (!pageContent) return [];

  const rawSentences = pageContent
    .split(/(?<=[.?!])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 5);

  const defaultIcons = ["📖", "👧", "👦", "👩‍🏫", "🌳", "✨", "🤝", "🌟", "💡", "🎒", "📚"];
  const defaultColors = ["blue", "emerald", "amber", "purple", "indigo", "rose"];

  return rawSentences.map((sentence, idx) => {
    const isDialogue = sentence.startsWith('"') || sentence.includes('said') || sentence.includes('asked');
    return {
      sentence_id: `${lessonId}-${pageNumber}-${idx + 1}`,
      lesson_id: lessonId,
      page_number: pageNumber,
      sentence_text: sentence,
      speaker: isDialogue ? "Story Character" : "Story Narrator",
      speaker_avatar: defaultIcons[idx % defaultIcons.length],
      scene_title: `Sentence ${idx + 1}`,
      scene_image_url: pageImageUrl || `/images/stories/l${Math.min(lessonId, 15)}_s${(idx % 4) + 1}.svg`,
      action_tag: isDialogue ? "💬 Character Dialogue" : "📖 Story Action",
      cue_color: defaultColors[idx % defaultColors.length],
    };
  });
}
